export const mockEvents = [
  {
    id: "1",
    title: "Campus Hackathon 2026",
    category: "Hackathon",
    description: "Build innovative solutions with your campus community in an intense 24-hour coding sprint. Food, swags & top prize pool included!",
    date: "September 20, 2026",
    time: "10:00 AM",
    venue: "Main Auditorium",
    organizer: "Computer Science Club",
    participantCount: 83,
    featured: true,
  },
  {
    id: "2",
    title: "Generative AI Workshop",
    category: "Workshops",
    description: "Hands-on masterclass on building modern LLM applications, prompt engineering techniques, and RAG pipelines.",
    date: "September 24, 2026",
    time: "02:00 PM",
    venue: "Innovation Hub Lab 3",
    organizer: "AI & ML Society",
    participantCount: 45,
    featured: true,
  },
  {
    id: "3",
    title: "Annual Campus Sports Meet",
    category: "Sports",
    description: "Compete in track & field, basketball, badminton, and soccer. Represent your department and win trophies!",
    date: "October 02, 2026",
    time: "08:00 AM",
    venue: "Central Athletic Ground",
    organizer: "Sports Board",
    participantCount: 156,
    featured: true,
  },
  {
    id: "4",
    title: "Autumn Cultural Festival",
    category: "Cultural",
    description: "A celebration of music, dance, theater, and art featuring student bands, dance troupes, and local food stalls.",
    date: "October 10, 2026",
    time: "05:00 PM",
    venue: "Open Air Theater",
    organizer: "Cultural Committee",
    participantCount: 240,
    featured: false,
  },
  {
    id: "5",
    title: "Robotics & Hardware Showcase",
    category: "Competitions",
    description: "Showcase your robotics models, IoT prototypes, and automation devices to industry judges and peers.",
    date: "October 15, 2026",
    time: "11:00 AM",
    venue: "Robotics Center Hall B",
    organizer: "Robotics Club",
    participantCount: 62,
    featured: false,
  },
  {
    id: "6",
    title: "Tech Career & Internship Symposium",
    category: "Seminars",
    description: "Network with top hiring partners, attend resume reviews, and discover winter internship opportunities.",
    date: "October 22, 2026",
    venue: "Placement Center Complex",
    organizer: "Training & Placement Cell",
    // participantCount & time left undefined intentionally to test fallback handling
    featured: false,
  }
];

export const mockCategories = [
  { name: "Technology", icon: "Code", count: "24 Events" },
  { name: "Hackathons", icon: "Zap", count: "8 Events" },
  { name: "Workshops", icon: "Wrench", count: "18 Events" },
  { name: "Seminars", icon: "BookOpen", count: "12 Events" },
  { name: "Cultural", icon: "Music", count: "15 Events" },
  { name: "Sports", icon: "Trophy", count: "10 Events" },
  { name: "Competitions", icon: "Target", count: "14 Events" },
  { name: "Clubs", icon: "Users", count: "35 Clubs" },
];
